version: '3'
services:
  web:
    container_name: todo_app
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www/html
    command: > 
      sh -c "apache2-foreground"  
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: example_user_password
    volumes:
      - ./todo-data:/var/lib/mysql
    ports:
     - '3306:3306'
volumes:
  todo-data:

