CREATE DATABASE IF NOT EXISTS todo_db;


CREATE TABLE IF NOT EXISTS usuario(
id_usuario INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
email VARCHAR(200) NOT NULL UNIQUE,
senha VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS tarefa(
id_tarefa INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
titulo VARCHAR(45) NOT NULL,
descricao VARCHAR(250),
data DATE NOT NULL,
tempo TIME,  
status VARCHAR(255) NOT NULL,  
id_usuario INT NOT NULL REFERENCES usuario
);

